research_task:
  description: >
    Conduct a thorough research about {ticker} + {headline} + {content}
    Make sure you find any interesting and relevant information given
    the current year is 2025.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {ticker} + {headline}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: researcher

market_data_analysis_task:
  description: >
    Analyze {ticker} market data to identify:
    - Price trends and patterns
    - Volume analysis
    - Technical indicators (RSI, MACD, Moving Averages)
    - Market sentiment indicators
    If analysis reveals unusual patterns or requires deeper investigation,
    delegate to the research agent for additional context.
  expected_output: >
    A detailed market analysis report containing:
    1. Technical analysis summary
    2. Volume profile analysis
    3. Key price levels identified
    4. Areas flagged for deeper research
  agent: financial_analyst
  delegation_triggers:
    - Unusual volume spikes
    - Unexpected price movements
    - Conflicting technical signals

strategy_validation_task:
  description: >
    Review and validate trading strategy for {ticker} by:
    - Analyzing historical performance
    - Checking current market conditions
    - Evaluating risk metrics
    Request additional research if market conditions are unclear
    or historical data shows anomalies.
  expected_output: >
    Strategy validation report including:
    1. Strategy viability score (1-10)
    2. Key risk factors identified
    3. Recommended adjustments
    4. Research requests made and findings
    5. Execution tool and strategy that will be executed
  agent: financial_analyst
  # collaboration_required: ["researcher", "news_monitor"]
  collaboration_required: ["researcher"]

deep_research_task:
  description: >
    Based on delegation from financial analyst, investigate research points:
    
    Focus areas:
    - SEC filings analysis
    - Company fundamentals
    - Industry comparisons
    - News impact assessment
  expected_output: >
    Research findings package:
    1. Detailed analysis per research point
    2. Supporting evidence and sources
    3. Recommendations for strategy adjustment
    4. Risk considerations identified
  agent: researcher
  callback_agent: financial_analyst
